=== Dorus-coder/OpenGym/layouts/improved_term/episode_220/stelloco.template.dtd
<!ELEMENT Stelloco (Stelloco_name,Stelloco_set+)>
  <!ELEMENT Stelloco_name (#PCDATA)>
  <!ELEMENT Stelloco_set (Stelloco_set_number,Stelloco_set_name,Global_settings,Settings_loading_condition)>
    <!ELEMENT Stelloco_set_number (#PCDATA)>
    <!ELEMENT Stelloco_set_name (#PCDATA)>
    <!ELEMENT Global_settings (Density_outside_water,Design_draft,Summer_draft,Tropical_draft,Winter_draft,Winter_north_atlantic_draft,Fresh_water_draft,Tropical_fresh_water_draft,Allowable_max_trims,Draft_marks,Hullforms,Weight_items,Environmental_variables,Openings,Damage_cases,Stability_calculation_including_shift_COG_liquid,Copy_files,Selected_set_damage_stability_criteria_final,Selected_set_damage_stability_criteria_intermediate,Selectable_set_longitudinal_strength_criteria,Selectable_set_intact_stability_criteria,Selectable_set_intermediate_stability_criteria,Selectable_set_final_stability_criteria,Name_LSH_contour_not_drawn)>
      <!ELEMENT Density_outside_water (#PCDATA)>
      <!ELEMENT Design_draft (#PCDATA)>
      <!ELEMENT Summer_draft (#PCDATA)>
      <!ELEMENT Tropical_draft (#PCDATA)>
      <!ELEMENT Winter_draft (#PCDATA)>
      <!ELEMENT Winter_north_atlantic_draft (#PCDATA)>
      <!ELEMENT Fresh_water_draft (#PCDATA)>
      <!ELEMENT Tropical_fresh_water_draft (#PCDATA)>
      <!ELEMENT Allowable_max_trims (Allowable_max_trim+)>
        <!ELEMENT Allowable_max_trim (Draft,Minimum_trim,Maximum_trim)>
          <!ELEMENT Draft (#PCDATA)>
          <!ELEMENT Minimum_trim (#PCDATA)>
          <!ELEMENT Maximum_trim (#PCDATA)>
      <!ELEMENT Draft_marks (Draft_mark+)>
        <!ELEMENT Draft_mark (Draft_mark_ID,Draft_mark_mean_BBSB,Draft_mark_checks,Local_min,Local_max)>
          <!ELEMENT Draft_mark_ID (ID_type+,ID_value+)>
            <!ELEMENT ID_type (#PCDATA)>
            <!ELEMENT ID_value (#PCDATA)>
          <!ELEMENT Draft_mark_mean_BBSB (#PCDATA)>
          <!ELEMENT Draft_mark_checks (Draft_mark_check+)>
            <!ELEMENT Draft_mark_check (#PCDATA)>
          <!ELEMENT Local_min (#PCDATA)>
          <!ELEMENT Local_max (#PCDATA)>
      <!ELEMENT Hullforms (Hullform+)>
        <!ELEMENT Hullform (Hullform_ID,Hullform_permeability,Hullform_longitudinal_distance,Hullform_vertical_distance,Hullform_transversal_distance)>
          <!ELEMENT Hullform_ID (ID_type+,ID_value+)>
            <!ELEMENT ID_type (#PCDATA)>
            <!ELEMENT ID_value (#PCDATA)>
          <!ELEMENT Hullform_permeability (#PCDATA)>
          <!ELEMENT Hullform_longitudinal_distance (#PCDATA)>
          <!ELEMENT Hullform_vertical_distance (#PCDATA)>
          <!ELEMENT Hullform_transversal_distance (#PCDATA)>
      <!ELEMENT Weight_items (Remove_weight_item+,Add_weight_item+)>
        <!ELEMENT Remove_weight_item (Remove_weight_item_ID)>
          <!ELEMENT Remove_weight_item_ID (ID_type+,ID_value+)>
            <!ELEMENT ID_type (#PCDATA)>
            <!ELEMENT ID_value (#PCDATA)>
        <!ELEMENT Add_weight_item (Name,Weight,VCG,LCG,TCG,FSM,Weight_group_number,Aft_boundary,Forward_boundary)>
          <!ELEMENT Name (#PCDATA)>
          <!ELEMENT Weight (#PCDATA)>
          <!ELEMENT VCG (#PCDATA)>
          <!ELEMENT LCG (#PCDATA)>
          <!ELEMENT TCG (#PCDATA)>
          <!ELEMENT FSM (#PCDATA)>
          <!ELEMENT Weight_group_number (#PCDATA)>
          <!ELEMENT Aft_boundary (#PCDATA)>
          <!ELEMENT Forward_boundary (#PCDATA)>
      <!ELEMENT Environmental_variables (Environmental_variable+)>
        <!ELEMENT Environmental_variable (Variable,Argument)>
          <!ELEMENT Variable (#PCDATA)>
          <!ELEMENT Argument (#PCDATA)>
      <!ELEMENT Openings (Opening_ID)>
        <!ELEMENT Opening_ID (ID_type+,ID_value+)>
          <!ELEMENT ID_type (#PCDATA)>
          <!ELEMENT ID_value (#PCDATA)>
      <!ELEMENT Damage_cases (Damage_case_ID)>
        <!ELEMENT Damage_case_ID (ID_type+,ID_value+)>
          <!ELEMENT ID_type (#PCDATA)>
          <!ELEMENT ID_value (#PCDATA)>
      <!ELEMENT Stability_calculation_including_shift_COG_liquid (#PCDATA)>
      <!ELEMENT Copy_files (Copy_file+)>
        <!ELEMENT Copy_file (Source,Destination,Conditional_copy,Action_after_copying)>
          <!ELEMENT Source (#PCDATA)>
          <!ELEMENT Destination (#PCDATA)>
          <!ELEMENT Conditional_copy (#PCDATA)>
          <!ELEMENT Action_after_copying (#PCDATA)>
      <!ELEMENT Selected_set_damage_stability_criteria_final (#PCDATA)>
      <!ELEMENT Selected_set_damage_stability_criteria_intermediate (#PCDATA)>
      <!ELEMENT Selectable_set_longitudinal_strength_criteria (Strength_ID)>
        <!ELEMENT Strength_ID (ID_type+,ID_value+)>
          <!ELEMENT ID_type (#PCDATA)>
          <!ELEMENT ID_value (#PCDATA)>
      <!ELEMENT Selectable_set_intact_stability_criteria (Criteria_ID)>
        <!ELEMENT Criteria_ID (ID_type+,ID_value+)>
          <!ELEMENT ID_type (#PCDATA)>
          <!ELEMENT ID_value (#PCDATA)>
      <!ELEMENT Selectable_set_intermediate_stability_criteria (Criteria_ID)>
        <!ELEMENT Criteria_ID (ID_type+,ID_value+)>
          <!ELEMENT ID_type (#PCDATA)>
          <!ELEMENT ID_value (#PCDATA)>
      <!ELEMENT Selectable_set_final_stability_criteria (Criteria_ID)>
        <!ELEMENT Criteria_ID (ID_type+,ID_value+)>
          <!ELEMENT ID_type (#PCDATA)>
          <!ELEMENT ID_value (#PCDATA)>
      <!ELEMENT Name_LSH_contour_not_drawn (Contour_ID)>
        <!ELEMENT Contour_ID (ID_type+,ID_value+)>
          <!ELEMENT ID_type (#PCDATA)>
          <!ELEMENT ID_value (#PCDATA)>
    <!ELEMENT Settings_loading_condition (Selected_set_longitudinal_strength,Selected_set_intact_stability_criteria,Maximum_draft,Additional_drafts,Check_maximum_trim)>
      <!ELEMENT Selected_set_longitudinal_strength (#PCDATA)>
      <!ELEMENT Selected_set_intact_stability_criteria (#PCDATA)>
      <!ELEMENT Maximum_draft (#PCDATA)>
      <!ELEMENT Additional_drafts (Additional_draft+)>
        <!ELEMENT Additional_draft (Additional_draft_ID,Additional_draft_check)>
          <!ELEMENT Additional_draft_ID (ID_type+,ID_value+)>
            <!ELEMENT ID_type (#PCDATA)>
            <!ELEMENT ID_value (#PCDATA)>
          <!ELEMENT Additional_draft_check (#PCDATA)>
      <!ELEMENT Check_maximum_trim (#PCDATA)>

=== Dorus-coder/OpenGym/layouts/imporved_reward/episode_7/stelloco.template.xml
<?xml version ="1.0"?>
<!DOCTYPE Stelloco SYSTEM "c:\users\cursist\dorus\thesisresearch\piasexamplefiles\notrans\stelloco.template.dtd">
<!-- Generated by PIAS -->
<Stelloco>
  <SARC_XML_dictionary_version>3</SARC_XML_dictionary_version>
  <Stelloco_name>Stelloco_name</Stelloco_name>
  <Stelloco_set>
    <Stelloco_set_number>Stelloco_set_number</Stelloco_set_number>
    <Stelloco_set_name>Stelloco_set_name</Stelloco_set_name>
    <Global_settings>
      <Density_outside_water>Density_outside_water</Density_outside_water>
      <Design_draft>Design_draft</Design_draft>
      <Summer_draft>Summer_draft</Summer_draft>
      <Tropical_draft>Tropical_draft</Tropical_draft>
      <Winter_draft>Winter_draft</Winter_draft>
      <Winter_north_atlantic_draft>Winter_north_atlantic_draft</Winter_north_atlantic_draft>
      <Fresh_water_draft>Fresh_water_draft</Fresh_water_draft>
      <Tropical_fresh_water_draft>Tropical_fresh_water_draft</Tropical_fresh_water_draft>
      <Allowable_max_trims>
        <Allowable_max_trim>
          <Draft>Draft</Draft>
          <Minimum_trim>Minimum_trim</Minimum_trim>
          <Maximum_trim>Maximum_trim</Maximum_trim>
        </Allowable_max_trim>
      </Allowable_max_trims>
      <Draft_marks>
        <Draft_mark>
          <Draft_mark_ID>
            <ID_type>ID_type</ID_type>
            <ID_value>ID_value</ID_value>
          </Draft_mark_ID>
          <Draft_mark_mean_BBSB>Draft_mark_mean_BBSB</Draft_mark_mean_BBSB>
          <Draft_mark_checks>
            <Draft_mark_check>Draft_mark_check</Draft_mark_check>
          </Draft_mark_checks>
          <Local_min>Local_min</Local_min>
          <Local_max>Local_max</Local_max>
        </Draft_mark>
      </Draft_marks>
      <Hullforms>
        <Hullform>
          <Hullform_ID>
            <ID_type>ID_type</ID_type>
            <ID_value>ID_value</ID_value>
          </Hullform_ID>
          <Hullform_permeability>Hullform_permeability</Hullform_permeability>
          <Hullform_longitudinal_distance>Hullform_longitudinal_distance</Hullform_longitudinal_distance>
          <Hullform_vertical_distance>Hullform_vertical_distance</Hullform_vertical_distance>
          <Hullform_transversal_distance>Hullform_transversal_distance</Hullform_transversal_distance>
        </Hullform>
      </Hullforms>
      <Weight_items>
        <Remove_weight_item>
          <Remove_weight_item_ID>
            <ID_type>ID_type</ID_type>
            <ID_value>ID_value</ID_value>
          </Remove_weight_item_ID>
        </Remove_weight_item>
        <Add_weight_item>
          <Name>Name</Name>
          <Weight>Weight</Weight>
          <VCG>VCG</VCG>
          <LCG>LCG</LCG>
          <TCG>TCG</TCG>
          <FSM>FSM</FSM>
          <Weight_group_number>Weight_group_number</Weight_group_number>
          <Aft_boundary>Aft_boundary</Aft_boundary>
          <Forward_boundary>Forward_boundary</Forward_boundary>
        </Add_weight_item>
      </Weight_items>
      <Environmental_variables>
        <Environmental_variable>
          <Variable>Variable</Variable>
          <Argument>Argument</Argument>
        </Environmental_variable>
      </Environmental_variables>
      <Openings>
        <Opening_ID>
          <ID_type>ID_type</ID_type>
          <ID_value>ID_value</ID_value>
        </Opening_ID>
      </Openings>
      <Damage_cases>
        <Damage_case_ID>
          <ID_type>ID_type</ID_type>
          <ID_value>ID_value</ID_value>
        </Damage_case_ID>
      </Damage_cases>
      <Stability_calculation_including_shift_COG_liquid>Stability_calculation_including_shift_COG_liquid</Stability_calculation_including_shift_COG_liquid>
      <Copy_files>
        <Copy_file>
          <Source>Source</Source>
          <Destination>Destination</Destination>
          <Conditional_copy>Conditional_copy</Conditional_copy>
          <Action_after_copying>Action_after_copying</Action_after_copying>
        </Copy_file>
      </Copy_files>
      <Selected_set_damage_stability_criteria_final>Selected_set_damage_stability_criteria_final</Selected_set_damage_stability_criteria_final>
      <Selected_set_damage_stability_criteria_intermediate>Selected_set_damage_stability_criteria_intermediate</Selected_set_damage_stability_criteria_intermediate>
      <Selectable_set_longitudinal_strength_criteria>
        <Strength_ID>
          <ID_type>ID_type</ID_type>
          <ID_value>ID_value</ID_value>
        </Strength_ID>
      </Selectable_set_longitudinal_strength_criteria>
      <Selectable_set_intact_stability_criteria>
        <Criteria_ID>
          <ID_type>ID_type</ID_type>
          <ID_value>ID_value</ID_value>
        </Criteria_ID>
      </Selectable_set_intact_stability_criteria>
      <Selectable_set_intermediate_stability_criteria>
        <Criteria_ID>
          <ID_type>ID_type</ID_type>
          <ID_value>ID_value</ID_value>
        </Criteria_ID>
      </Selectable_set_intermediate_stability_criteria>
      <Selectable_set_final_stability_criteria>
        <Criteria_ID>
          <ID_type>ID_type</ID_type>
          <ID_value>ID_value</ID_value>
        </Criteria_ID>
      </Selectable_set_final_stability_criteria>
      <Name_LSH_contour_not_drawn>
        <Contour_ID>
          <ID_type>ID_type</ID_type>
          <ID_value>ID_value</ID_value>
        </Contour_ID>
      </Name_LSH_contour_not_drawn>
    </Global_settings>
    <Settings_loading_condition>
      <Selected_set_longitudinal_strength>Selected_set_longitudinal_strength</Selected_set_longitudinal_strength>
      <Selected_set_intact_stability_criteria>Selected_set_intact_stability_criteria</Selected_set_intact_stability_criteria>
      <Maximum_draft>Maximum_draft</Maximum_draft>
      <Additional_drafts>
        <Additional_draft>
          <Additional_draft_ID>
            <ID_type>ID_type</ID_type>
            <ID_value>ID_value</ID_value>
          </Additional_draft_ID>
          <Additional_draft_check>Additional_draft_check</Additional_draft_check>
        </Additional_draft>
      </Additional_drafts>
      <Check_maximum_trim>Check_maximum_trim</Check_maximum_trim>
    </Settings_loading_condition>
  </Stelloco_set>
</Stelloco>
